Repository Sodamii/Sodam, pull requests merged in 2025-02, with the labels that each got.

#73 [Fix] 글 작성 뷰 UI 레이아웃 및 버그 수정
  Sodam/Sodam.xcodeproj/project.pbxproj
  Sodam/Sodam/Configuration/Info.plist
  Sodam/Sodam/WriteView/WriteView.swift
  Sodam/Sodam/WriteView/WriteViewController.swift
Labels: bug

#70 [Feat] 이미지 연결
  Sodam/Sodam/HangdamStorage/HangdamStorageView.swift
  Sodam/Sodam/HappinessDetail/HappinessDetailView.swift
  Sodam/Sodam/HappinessDetail/HappinessDetailViewModel.swift
  Sodam/Sodam/HappinessList/HappinessListView.swift
  Sodam/Sodam/HappinessList/HappinessListViewModel.swift
  Sodam/Sodam/Repository/HappinessRepository.swift
Labels: enhancement

#77 [Fix] reload 버그와 endDate UI 버그 수정
  Sodam/Sodam/CoreData/DTO/HangdamDTO.swift
  Sodam/Sodam/HangdamStatusView.swift
  Sodam/Sodam/HangdamStorage/HangdamGridView.swift
  Sodam/Sodam/Main/View/MainMessages.swift
  Sodam/Sodam/Main/View/MainViewController.swift
  Sodam/Sodam/Main/View/MainViewModel.swift
  Sodam/Sodam/WriteView/WriteView.swift
  Sodam/Sodam/WriteView/WriteViewController.swift
  Sodam/Sodam/WriteView/WriteViewModel.swift
Labels: bug

#81 [Fix] Data -[String] 변환 코드 경고 메시지 내용 반영
  Sodam/Sodam.xcodeproj/project.pbxproj
  Sodam/Sodam/CoreData/CoreDataManager.swift
  Sodam/Sodam/Extension/+Data.swift
  Sodam/Sodam/Main/View/MainViewController.swift
  Sodam/Sodam/Manager/UserDefaultsManager.swift
  Sodam/Sodam/Repository/HangdamRepository.swift
  Sodam/Sodam/Repository/HappinessRepository.swift
  Sodam/Sodam/WriteView/WriteViewController.swift
Labels: bug

#85 [Fix] WriteViewController 메모리 누수 해결
  Sodam/Sodam/Extension/+Notification.swift
  Sodam/Sodam/Main/View/MainViewController.swift
  Sodam/Sodam/WriteView/WriteViewController.swift
Labels: bug

#86 [Fix] 행복 리스트 뷰 셀 분리
  Sodam/Sodam/HappinessList/HappinessCell.swift
  Sodam/Sodam/HappinessList/HappinessListView.swift
  Sodam/Sodam/HappinessList/HappinessListViewModel.swift
  Sodam/Sodam/Manager/ImageManager.swift
  Sodam/Sodam/Repository/HappinessRepository.swift
Labels: bug

#90 [Modify] 알럿 케이스 분기
  Sodam/Sodam/WriteView/WriteViewController.swift
Labels: enhancement

#97 [Fix] 작성뷰 레이아웃 수정
  Sodam/Sodam/View/Main/WriteView/WriteView.swift
  Sodam/Sodam/View/Main/WriteView/WriteViewController.swift
  Sodam/Sodam/View/Main/WriteView/WriteViewModel.swift
Labels: enhancement

#99 [Feat] 행복 날짜 format 고정
  Sodam/Sodam/Extension/+Date.swift
  Sodam/Sodam/Model/DTO/HangdamDTO.swift
  Sodam/Sodam/Model/DTO/HappinessDTO.swift
  Sodam/Sodam/View/Main/WriteView/WriteView.swift
  Sodam/Sodam/View/Storage/HappinessDetail/HappinessDetailView.swift
  Sodam/Sodam/View/Storage/HappinessList/HappinessCell.swift
Labels: enhancement

#109 [Fix] 행담이 보관함 emptyview 작은 화면 대응
  Sodam/Sodam/View/Storage/HangdamEmptyView.swift
  Sodam/Sodam/View/Storage/HangdamStorageView.swift
Labels: bug

#113 [Refactor] DTO mapper
  Sodam/Sodam/Model/DTO/DTOMapper.swift
  Sodam/Sodam/Model/DTO/HangdamDTO.swift
  Sodam/Sodam/Model/DTO/HappinessDTO.swift
  Sodam/Sodam/Model/Manager/CoreDataManager.swift
  Sodam/Sodam/Model/Repository/HangdamRepository.swift
  Sodam/Sodam/Model/Repository/HappinessRepository.swift
Labels: refactor

#110 [Refactor] LocalNotificationManager 리팩토링, ToastManager 추가
  Sodam/Sodam/Delegate/AppDelegate.swift
  Sodam/Sodam/Delegate/SceneDelegate.swift
  Sodam/Sodam/Model/Manager/AlertManager.swift
  Sodam/Sodam/Model/Manager/LocalNotificationManager.swift
  Sodam/Sodam/Model/Manager/ToastManager.swift
  Sodam/Sodam/Model/Manager/UserDefaultsManager.swift
  Sodam/Sodam/View/Main/MainView/MainViewController.swift
  Sodam/Sodam/View/Setting/SettingViewModel.swift
  Sodam/Sodam/View/Setting/SettingsViewController.swift
Labels: refactor

#117 [Refactor] happiness cell
  Sodam/Sodam/View/List/HappinessList/HappinessCell.swift
  Sodam/Sodam/View/List/HappinessList/HappinessListView.swift
Labels: enhancement

#121 [Modify] 줄 간격 및 버튼 색깔 수정
  Sodam/Sodam/View/Main/WriteView/ImageCollectionViewCell.swift
  Sodam/Sodam/View/Main/WriteView/WriteView.swift
  Sodam/Sodam/View/Main/WriteView/WriteViewController.swift
Labels: enhancement

#126 [Refactor] 알럿 매니저 리팩토링 (메인뷰컨,작성뷰컨 알럿부분 수정)
  Sodam/Sodam/Model/Manager/AlertManager.swift
  Sodam/Sodam/View/Main/MainView/Helper/ForbiddenWords.swift
  Sodam/Sodam/View/Main/MainView/MainViewController.swift
  Sodam/Sodam/View/Main/WriteView/WriteViewController.swift
Labels: refactor

#129 [Refactor] 메인 메세지 추가 및 수정, 줄 간격 넓히기
  Sodam/Sodam/View/Main/MainView/Helper/MainMessages.swift
  Sodam/Sodam/View/Main/MainView/MainView.swift
Labels: refactor

#140 [Fix] Happiness list view sync bug
  Sodam/Sodam/View/List/HappinessList/HappinessListView.swift
  Sodam/Sodam/View/List/HappinessList/HappinessListViewModel.swift
  Sodam/Sodam/View/Storage/HangdamGridView.swift
  Sodam/Sodam/View/TabBar/CustomTabBarController.swift
Labels: bug

#143 (수정) [Refactor] alert enum 리팩토링 및 메인메세지 수정
  Sodam/Sodam/Model/Manager/Alert/AlertManager.swift
  Sodam/Sodam/Model/Manager/Alert/AlertTypes.swift
  Sodam/Sodam/View/Main/MainView/Helper/MainMessages.swift
  Sodam/Sodam/View/Main/MainView/MainViewController.swift
  Sodam/Sodam/View/Main/WriteView/WriteViewController.swift
Labels: refactor

#147 [Fix] Navigation 쌓였을 때 Tabbar 처리
  Sodam/Sodam/Helper/TabBarHelper.swift
  Sodam/Sodam/View/List/HappinessDetail/HappinessDetailView.swift
  Sodam/Sodam/View/List/HappinessList/HappinessListView.swift
  Sodam/Sodam/View/Storage/HangdamStorageView.swift
Labels: bug

#136 [ Fix] 설정 뷰 버그 수정
  Sodam/Sodam/Model/Manager/LocalNotificationManager.swift
  Sodam/Sodam/Model/Manager/UserDefaultsManager.swift
  Sodam/Sodam/View/Main/WriteView/WriteViewModel.swift
  Sodam/Sodam/View/Setting/Helper/Setting.swift
  Sodam/Sodam/View/Setting/SettingViewModel.swift
  Sodam/Sodam/View/Setting/SettingsViewController.swift
Labels: bug, refactor

#137 [Refactor] 행담이 보관함 뷰 코드 리팩토링
  Sodam/Sodam.xcodeproj/project.pbxproj
  Sodam/Sodam/Helper/TabBarHelper.swift
  Sodam/Sodam/Model/DTO/HappinessDTO.swift
  Sodam/Sodam/View/List/HappinessList/HangdamStatusView.swift
  Sodam/Sodam/View/List/HappinessList/HappinessCell.swift
  Sodam/Sodam/View/List/HappinessList/HappinessListView.swift
  Sodam/Sodam/View/List/HappinessList/HappinessListViewModel.swift
  Sodam/Sodam/View/Storage/HangdamGridView.swift
  Sodam/Sodam/View/Storage/HangdamStorageView.swift
  Sodam/Sodam/View/Storage/HangdamStorageViewModel.swift
  Sodam/Sodam/View/TabBar/CustomTabBarController.swift
Labels: refactor

#146 [Refactor] List, Storage 탭에 속한 뷰들의 의존성 리팩터링
  Sodam/Sodam/Extension/+Result+Fold.swift
  Sodam/Sodam/Model/Manager/CoreDataManager.swift
  Sodam/Sodam/Model/Repository/HangdamRepository.swift
  Sodam/Sodam/Model/Repository/HappinessRepository.swift
  Sodam/Sodam/View/List/HappinessCell/HappinessCellView.swift
  Sodam/Sodam/View/List/HappinessCell/HappinessCellViewModel.swift
  Sodam/Sodam/View/List/HappinessDetail/HappinessDetailView.swift
  Sodam/Sodam/View/List/HappinessDetail/HappinessDetailViewModel.swift
  Sodam/Sodam/View/List/HappinessList/HangdamStatusView.swift
  Sodam/Sodam/View/List/HappinessList/HappinessListView.swift
  Sodam/Sodam/View/List/HappinessList/HappinessListViewModel.swift
  Sodam/Sodam/View/List/Helper/DataMapper/DataMappingProtocol.swift
  Sodam/Sodam/View/List/Helper/DataMapper/HappinessListConfigMapper.swift
  Sodam/Sodam/View/List/Helper/DataMapper/HappinessListContentMapper.swift
  Sodam/Sodam/View/List/Helper/DataMapper/MapperFacotry/DataMapperFactory.swift
  Sodam/Sodam/View/List/Helper/DataMapper/StatusContentMapper.swift
  Sodam/Sodam/View/List/Helper/DataStruct/HappinessCellContent.swift
  Sodam/Sodam/View/List/Helper/DataStruct/HappinessDetailContent.swift
  Sodam/Sodam/View/List/Helper/DataStruct/HappinessListConfig.swift
  Sodam/Sodam/View/List/Helper/DataStruct/HappinessListContent.swift
  Sodam/Sodam/View/List/Helper/DataStruct/StatusContent.swift
  Sodam/Sodam/View/List/Helper/Operator/CellThumnailFetcher.swift
  Sodam/Sodam/View/List/Helper/Operator/DerailViewOperator.swift
  Sodam/Sodam/View/List/Helper/Operator/HappinessListViewReloder.swift
  Sodam/Sodam/View/Storage/HangdamGridView.swift
  Sodam/Sodam/View/Storage/HangdamStorageViewModel.swift
  Sodam/Sodam/View/TabBar/CustomTabBarController.swift
Labels: refactor

#149 [Fix] Storage view rendering bug
  Sodam/Sodam/View/Storage/HangdamStorageView.swift
Labels: bug

#150 [Fix] Back action gesture bug
  Sodam/Sodam/View/List/HappinessDetail/HappinessDetailView.swift
Labels: bug

#155 [Fix] 작성 뷰 키보드 버그 수정 / 메모리누수 해결
  Sodam/Sodam/View/Main/WriteView/WriteView.swift
  Sodam/Sodam/View/Main/WriteView/WriteViewController.swift
Labels: bug

#154 Fix/UI bug
  Sodam/Sodam/Model/Manager/ImageManager.swift
  Sodam/Sodam/Model/Repository/HappinessRepository.swift
  Sodam/Sodam/View/List/HappinessCell/HappinessCellView.swift
  Sodam/Sodam/View/List/HappinessDetail/HappinessDetailView.swift
  Sodam/Sodam/View/List/HappinessList/HappinessListView.swift
  Sodam/Sodam/View/List/Helper/Operator/DerailViewOperator.swift
Labels: bug

#158 [Feat] 글자수 제한 기능 및 입력한 글자수 표기 추가
  Sodam/Sodam/Model/Manager/Alert/AlertTypes.swift
  Sodam/Sodam/View/Main/WriteView/WriteView.swift
  Sodam/Sodam/View/Main/WriteView/WriteViewController.swift
Labels: enhancement

#159 [Fix] 일기 작성 시간 확인 후 알림시간 전 작성완료 시 알림 안울리게 코드 수정
  Sodam/Sodam/Delegate/SceneDelegate.swift
  Sodam/Sodam/Model/Manager/Alert/AlertManager.swift
  Sodam/Sodam/Model/Manager/LocalNotificationManager.swift
  Sodam/Sodam/Model/Manager/UserDefaultsManager.swift
  Sodam/Sodam/View/Main/MainView/MainViewController.swift
  Sodam/Sodam/View/Main/MainView/MainViewModel.swift
  Sodam/Sodam/View/Main/WriteView/WriteViewModel.swift
  Sodam/Sodam/View/Setting/SettingViewModel.swift
  Sodam/Sodam/View/Setting/SettingsViewController.swift
Labels: bug, refactor

#164 [Feat] 사용자가 원하는 폰트로 설정할 수 있는 기능 추가
  Sodam/Sodam/Delegate/SceneDelegate.swift
  Sodam/Sodam/Model/Manager/LocalNotificationManager.swift
  Sodam/Sodam/Model/Manager/UserDefaultsManager.swift
  Sodam/Sodam/View/FontSetting/FontSettingTableViewCell.swift
  Sodam/Sodam/View/FontSetting/FontSettingViewController.swift
  Sodam/Sodam/View/FontSetting/FontSettingViewModel.swift
  Sodam/Sodam/View/Setting/Helper/Setting.swift
  Sodam/Sodam/View/Setting/SettingTableViewCell.swift
  Sodam/Sodam/View/Setting/SettingViewModel.swift
  Sodam/Sodam/View/Setting/SettingsViewController.swift
  Sodam/Sodam/View/TabBar/CustomTabBarController.swift
Labels: enhancement
