Repository Sodamii/Sodam, pull requests merged in 2025-01, with the labels that each got.

#15 [Feat] settingViewController UI 구현
  Sodam/Sodam/Extension/+Array.swift
  Sodam/Sodam/Extension/+UIStackView.swift
  Sodam/Sodam/Extension/+UIView.swift
  Sodam/Sodam/Setting/ReuseIdentifying.swift
  Sodam/Sodam/Setting/Setting.swift
  Sodam/Sodam/Setting/SettingsViewController.swift
  Sodam/Sodam/Setting/View/SettingTableViewCell.swift
  Sodam/Sodam/Setting/View/SettingView.swift
  Sodam/Sodam/SettingsViewController.swift
Labels: enhancement

#13 [Feat] 행담 보관 뷰
  Sodam/Sodam/Configuration/Assets.xcassets/babyHangdam.imageset/Contents.json
  Sodam/Sodam/Configuration/Assets.xcassets/babyHangdam.imageset/babyHangdam.png
  Sodam/Sodam/Extension/+Color.swift
  Sodam/Sodam/Extension/+Date.swift
  Sodam/Sodam/HangdamStatusView.swift
  Sodam/Sodam/HangdamStorage/HangdamGridView.swift
  Sodam/Sodam/HangdamStorage/HangdamStorageView.swift
  Sodam/Sodam/HangdamStorage/MockHangdam.swift
  Sodam/Sodam/Main/ViewModel/CustomTabBarController.swift
  Sodam/Sodam/MemoryViewController.swift
Labels: enhancement

#19 [Fix] TabBar Appearance 설정
  Sodam/Sodam/Main/ViewModel/CustomTabBarController.swift
Labels: bug

#24 [Feat] LocalNotifiacation 기능 구현
  Sodam/Sodam/Delegate/AppDelegate.swift
  Sodam/Sodam/Delegate/SceneDelegate.swift
  Sodam/Sodam/LocalNotificationManager.swift
  Sodam/Sodam/Setting/SettingsViewController.swift
  Sodam/Sodam/Setting/View/SettingTableViewCell.swift
Labels: enhancement

#31 [Refactor] 행담이 보관함 뷰 UI 업데이트 및 Navigation 추가
  Sodam/Sodam/HangdamStatusView.swift
  Sodam/Sodam/HangdamStorage/HangdamGridView.swift
  Sodam/Sodam/HangdamStorage/HangdamStorageView.swift
  Sodam/Sodam/HangdamStorage/MockHangdam.swift
  Sodam/Sodam/HangdamStorage/TestView.swift
Labels: enhancement

#34 [Refactor] 행담이 기록 뷰와 Navigation 연결
  Sodam/Sodam/HangdamStorage/HangdamGridView.swift
  Sodam/Sodam/HangdamStorage/HangdamStorageView.swift
  Sodam/Sodam/HangdamStorage/TestView.swift
  Sodam/Sodam/HappinessList/HappinessListView.swift
Labels: enhancement

#26 [Feat] 행담이 / 행복한 기억 CRUD
  Sodam/Sodam/CoreData/CoreDataManager.swift
  Sodam/Sodam/CoreData/DTO/HangdamDTO.swift
  Sodam/Sodam/CoreData/DTO/HappinessDTO.swift
  Sodam/Sodam/CoreData/DataError.swift
  Sodam/Sodam/CoreData/HangdamUpdateCase.swift
  Sodam/Sodam/CoreData/SodamContainer.xcdatamodeld/SodamContainer.xcdatamodel/contents
  Sodam/Sodam/Extension/+Data.swift
  Sodam/Sodam/Extension/+Date.swift
  Sodam/Sodam/HangdamStatusView.swift
  Sodam/Sodam/HangdamStorage/HangdamGridView.swift
  Sodam/Sodam/Helper/IDConverter.swift
  Sodam/Sodam/Repository/HangdamRepository.swift
  Sodam/Sodam/Repository/HappinessRepository.swift
Labels: enhancement, question

#35 [Fix] 컴파일 에러 해결
  Sodam/Sodam/HappinessList/HappinessListView.swift
Labels: bug

#39 [Fix] 탭바 사라지기 수정
  Sodam/Sodam/HangdamStorage/HangdamStorageView.swift
  Sodam/Sodam/HappinessList/HappinessListView.swift
Labels: bug

#44 [Feat] 행담이 보관함 코어 데이터 연결 완료
  Sodam/Sodam/CoreData/CoreDataManager.swift
  Sodam/Sodam/CoreData/DTO/HappinessDTO.swift
  Sodam/Sodam/CoreData/SodamContainer.xcdatamodeld/SodamContainer.xcdatamodel/contents
  Sodam/Sodam/HangdamStatusView.swift
  Sodam/Sodam/HangdamStorage/HangdamGridView.swift
  Sodam/Sodam/HangdamStorage/HangdamStorageView.swift
  Sodam/Sodam/HangdamStorage/HangdamStorageViewModel.swift
  Sodam/Sodam/HappinessDetail/HappinessDetailView.swift
  Sodam/Sodam/HappinessDetail/HappinessDetailViewModel.swift
  Sodam/Sodam/HappinessList/HappinessListView.swift
  Sodam/Sodam/HappinessList/HappinessListViewModel.swift
  Sodam/Sodam/Helper/CustomAlert/CustomAlertBuilder.swift
  Sodam/Sodam/Helper/CustomAlert/CustomAlertConfiguration.swift
  Sodam/Sodam/Helper/CustomAlert/CustomAlertViewController.swift
  Sodam/Sodam/Main/View/MainView.swift
  Sodam/Sodam/Main/View/MainViewController.swift
  Sodam/Sodam/Main/View/MainViewModel.swift
  Sodam/Sodam/Repository/HangdamRepository.swift
  Sodam/Sodam/Repository/HappinessRepository.swift
  Sodam/Sodam/WriteView/WriteViewController.swift
  Sodam/Sodam/WriteView/WriteViewModel.swift
Labels: enhancement

#53 [Feat] NotificationCenter로 레벨업 이벤트 전달
  Sodam/Sodam/Extension/+Notification.swift
  Sodam/Sodam/Main/View/MainViewModel.swift
  Sodam/Sodam/Repository/HappinessRepository.swift
Labels: enhancement

#61 [Refactor] change dependency
  Sodam/Sodam.xcodeproj/project.pbxproj
  Sodam/Sodam/CoreData/CoreDataManager.swift
  Sodam/Sodam/HangdamStorage/HangdamStorageView.swift
  Sodam/Sodam/HangdamStorage/HangdamStorageViewModel.swift
  Sodam/Sodam/HappinessDetail/HappinessDetailView.swift
  Sodam/Sodam/HappinessDetail/HappinessDetailViewModel.swift
  Sodam/Sodam/Main/View/CustomTabBarController.swift
  Sodam/Sodam/Main/View/MainViewController.swift
  Sodam/Sodam/Main/View/MainViewModel.swift
  Sodam/Sodam/Repository/HangdamRepository.swift
  Sodam/Sodam/Repository/HappinessRepository.swift
Labels: enhancement

#62 [Feat] 행담이 상태 뷰, 보관함 뷰 데이터 바인딩
  Sodam/Sodam/CoreData/DTO/HangdamDTO.swift
  Sodam/Sodam/Extension/+Image.swift
  Sodam/Sodam/HangdamStatusView.swift
  Sodam/Sodam/HangdamStorage/HangdamGridView.swift
  Sodam/Sodam/HangdamStorage/HangdamStorageView.swift
Labels: enhancement

#65 [Feat] FileManager로 이미지 삭제 구현
  Sodam/Sodam/Manager/FileError.swift
  Sodam/Sodam/Manager/ImageManager.swift
Labels: enhancement
